### ISSUE TITLE
NaNs in LAMF new_dff traces (tracking issue)

### ISSUE THREAD

**Issue by mattjdavis** [AllenInstitute/brain_observatory_analysis#7]
Discovered NaNs, compiling observations here

**Comment by mattjdavis** [comment]
## LAMF data with NaNs and total within ROIS



![Image](https://user-images.githubusercontent.com/9253879/224429679-42672957-0dc0-4ffd-8e45-89692be620ac.png)

**Comment by mattjdavis** [comment]
## Examples with high NaNs

![Image](https://user-images.githubusercontent.com/9253879/224429875-43e302ae-fd39-4b79-a5c6-445074c76e3f.png)


![Image](https://user-images.githubusercontent.com/9253879/224429888-6ad874ca-2ecf-473f-a599-94a1d4abdd93.png)



![Image](https://user-images.githubusercontent.com/9253879/224429910-58cfcdb9-5d91-48b1-9f12-a825f03c5bf1.png)

**Comment by mattjdavis** [comment]
## Linear Interpolation for events detection to run


![Image](https://user-images.githubusercontent.com/9253879/224429979-fc919e91-d0d1-48a2-85b2-25655a7167f5.png)

**Comment by yavorska-iryna** [comment]
These are off traces based on @jkim0731 's changes, right? Do you know if this happened in old off traces?

**Comment by jkim0731** [comment]
Also saw some NaN values at the beginning of the session, during gray screen periods. The # of NaN frames were variable among the neurons.

**Comment by mattjdavis** [comment]
@yavorska-iryna yes these are "new_dff" traces. I don't know the status of the old one

Seems notable that, at least these examples, the nan block occurs around high activity bouts

**Comment by jkim0731** [comment]
Leaving a note here: Seems like the NaN values are from edge cases (e.g., longer than 30 min of "active frames"), which is fixed by pika team code. I will incorporate the fix to the brain_observatory_qc/pipeline_dev/calculate_new_dff.py
